image: maven:3.6.3-jdk-11

stages:
  - test
  - deploy


test:
  stage: test
  script:
    - 'mvn test'

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - ./deploy_script_linux.sh
