spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mars?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ChatApp2019!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: callbackcats@gmail.com
    password: PwKQNNSs2yv94pLG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl.enable: false

logging:
  level:
    com.progmasters: info
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

google:
  apikey: AIzaSyAeQEHjfxVD8584aJATT0pSNBf3DuCr1h0

email:
  send:
    subject: Regisztráció megerősítése
    subjectPassword: Új jelszó igénylése
    text: Az alábbi linkre kattintva aktiválhatja fiókját
    textPassword: Az alábbi linkre kattintva megadhatja új jelszavát
    confirmation: http://localhost:4200/register-success/
    password: http://localhost:4200/new-password/
  elapsed-hours: 72

cors-policies: http://localhost:4200, http://127.0.0.1:4200

regex:
  validator:
    password: (?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{6,15})$
    email: ^[\w!#$%&’*+/=?`{|}~^-]+(?:\.[\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}$
    phone: ^\+(\d{1,2})\D*(\d{1,3})\D*(\d{3})\D*(\d{3,4})$
    webpage: (https?://(?:www.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\\s]{2,}|www.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\\s]{2,}|https?://(?:www.|(?!www))[a-zA-Z0-9]+.[^\\s]{2,}|www.[a-zA-Z0-9]+.[^\\s]{2,})

jwt:
  secret: marsjwtsupersecretkey

executor:
  corePoolSize: 20
  maxPoolSize: 200
  queueCapacity: 500

institution:
  zipcode:
    min: 999
    max: 10000
  description:
    min: 30
    max: 200